import React, { useEffect, useState } from "react";
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, InputLabel, MenuItem, Select, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from "@mui/material";
import PageContainer from "../../shared/components/layout/PageContainer";
import PageHeader from "../../shared/components/layout/PageHeader";
import { identityAdminApi } from "../../shared/api/mvpApi";
import { useAuth } from "../hooks/useAuth";

const emptyUser = { username: "", password: "", roleIds: [] };

export default function UsersPage() {
  const { user: currentUser } = useAuth(); const allowed = currentUser?.roles?.includes("MANAGEMENT");
  const [users, setUsers] = useState([]), [roles, setRoles] = useState([]), [permissions, setPermissions] = useState([]), [form, setForm] = useState(emptyUser), [roleForm, setRoleForm] = useState({ name: "", description: "" }), [permissionForm, setPermissionForm] = useState({ name: "", description: "" }), [editUser, setEditUser] = useState(null), [error, setError] = useState(""), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false);
  const load = async () => { setLoading(true); setError(""); try { const [userRows, roleRows, permissionRows] = await Promise.all([identityAdminApi.users(), identityAdminApi.roles(), identityAdminApi.permissions()]); setUsers(userRows); setRoles(roleRows); setPermissions(permissionRows); } catch (e) { setError(e.response?.data?.message || "Could not load identity administration data."); } finally { setLoading(false); } };
  useEffect(() => { if (allowed) load(); else setLoading(false); }, [allowed]);
  const createUser = async e => { e.preventDefault(); setSaving(true); try { await identityAdminApi.createUser({ ...form, roleIds: form.roleIds.map(Number) }); setForm(emptyUser); await load(); } catch (err) { setError(err.response?.data?.message || "Could not create user."); } finally { setSaving(false); } };
  const updateUser = async e => { e.preventDefault(); setSaving(true); try { const payload = { username: editUser.username, enabled: editUser.enabled }; if (editUser.password) payload.password = editUser.password; await identityAdminApi.updateUser(editUser.id, payload); setEditUser(null); await load(); } catch (err) { setError(err.response?.data?.message || "Could not update user."); } finally { setSaving(false); } };
  const disable = async target => { if (!window.confirm(`Disable ${target.username}?`)) return; setSaving(true); try { await identityAdminApi.disableUser(target.id); await load(); } catch (e) { setError(e.response?.data?.message || "Could not disable user."); } finally { setSaving(false); } };
  const createRole = async e => { e.preventDefault(); setSaving(true); try { await identityAdminApi.createRole(roleForm); setRoleForm({ name: "", description: "" }); await load(); } catch (err) { setError(err.response?.data?.message || "Could not create role."); } finally { setSaving(false); } };
  const createPermission = async e => { e.preventDefault(); setSaving(true); try { await identityAdminApi.createPermission(permissionForm); setPermissionForm({ name: "", description: "" }); await load(); } catch (err) { setError(err.response?.data?.message || "Could not create permission."); } finally { setSaving(false); } };
  if (!allowed) return <PageContainer><PageHeader title="User administration" subtitle="Identity and access management." /><Alert severity="warning">Management access is required to administer users.</Alert></PageContainer>;
  return <PageContainer><PageHeader title="User administration" subtitle="Provision accounts, control access and manage operational roles." />{error && <Alert severity="error" sx={{ mb: 2.5 }} onClose={() => setError("")}>{error}</Alert>}
    <Card sx={{ mb: 2.5 }}><CardContent component="form" onSubmit={createUser}><Typography variant="h6">Create user</Typography><Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>Passwords must contain at least eight characters.</Typography><Stack direction={{ xs: "column", lg: "row" }} spacing={1.5}><TextField required label="Username" value={form.username} onChange={e => setForm({ ...form, username: e.target.value })} /><TextField required type="password" label="Temporary password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} inputProps={{ minLength: 8 }} /><FormControl sx={{ minWidth: 260 }}><InputLabel>Roles</InputLabel><Select multiple label="Roles" value={form.roleIds} onChange={e => setForm({ ...form, roleIds: e.target.value })}>{roles.map(role => <MenuItem key={role.id} value={role.id}>{role.name}</MenuItem>)}</Select></FormControl><Button type="submit" variant="contained" disabled={saving}>Create user</Button></Stack></CardContent></Card>
    <Card sx={{ mb: 2.5 }}><Box sx={{ px: 2.5, py: 2, borderBottom: 1, borderColor: "divider" }}><Typography variant="h6">User accounts</Typography><Typography variant="body2" color="text.secondary">Active and disabled application access.</Typography></Box><TableContainer><Table><TableHead><TableRow><TableCell>User</TableCell><TableCell>Roles</TableCell><TableCell>Status</TableCell><TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{loading ? <TableRow><TableCell colSpan={4} align="center" sx={{ py: 5 }}><CircularProgress size={24} /></TableCell></TableRow> : users.map(account => <TableRow hover key={account.id}><TableCell><Typography variant="subtitle2">{account.username}</Typography><Typography variant="caption" color="text.secondary">Created {account.createdAt ? new Date(account.createdAt).toLocaleDateString("en-AU") : "—"}</Typography></TableCell><TableCell><Stack direction="row" spacing={.5} flexWrap="wrap">{account.roles.map(role => <Chip key={role.id} size="small" label={role.name} />)}</Stack></TableCell><TableCell><Chip size="small" color={account.enabled ? "success" : "default"} label={account.enabled ? "Enabled" : "Disabled"} /></TableCell><TableCell align="right"><Button size="small" onClick={() => setEditUser({ ...account, password: "" })}>Edit</Button>{account.enabled && <Button size="small" color="error" onClick={() => disable(account)} disabled={saving}>Disable</Button>}</TableCell></TableRow>)}{!loading && !users.length && <TableRow><TableCell colSpan={4} align="center" sx={{ py: 5 }}>No user accounts found.</TableCell></TableRow>}</TableBody></Table></TableContainer></Card>
    <Stack direction={{ xs: "column", lg: "row" }} spacing={2.5}><Card sx={{ flex: 1 }}><CardContent component="form" onSubmit={createRole}><Typography variant="h6">Roles</Typography><Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>Define business access groups.</Typography><Stack spacing={1.5}><TextField required label="Role name" value={roleForm.name} onChange={e => setRoleForm({ ...roleForm, name: e.target.value })} /><TextField label="Description" value={roleForm.description} onChange={e => setRoleForm({ ...roleForm, description: e.target.value })} /><Button type="submit" variant="outlined" disabled={saving}>Create role</Button>{roles.map(role => <Box key={role.id} sx={{ pt: 1, borderTop: 1, borderColor: "divider" }}><Typography variant="subtitle2">{role.name}</Typography><Typography variant="caption" color="text.secondary">{role.description || "No description"}</Typography></Box>)}</Stack></CardContent></Card><Card sx={{ flex: 1 }}><CardContent component="form" onSubmit={createPermission}><Typography variant="h6">Permissions</Typography><Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>Register granular permissions for future role mapping.</Typography><Stack spacing={1.5}><TextField required label="Permission name" value={permissionForm.name} onChange={e => setPermissionForm({ ...permissionForm, name: e.target.value })} /><TextField label="Description" value={permissionForm.description} onChange={e => setPermissionForm({ ...permissionForm, description: e.target.value })} /><Button type="submit" variant="outlined" disabled={saving}>Create permission</Button>{permissions.map(permission => <Box key={permission.id} sx={{ pt: 1, borderTop: 1, borderColor: "divider" }}><Typography variant="subtitle2">{permission.name}</Typography><Typography variant="caption" color="text.secondary">{permission.description || "No description"}</Typography></Box>)}</Stack></CardContent></Card></Stack>
    <Dialog open={Boolean(editUser)} onClose={() => !saving && setEditUser(null)} fullWidth maxWidth="xs"><Box component="form" onSubmit={updateUser}><DialogTitle>Edit user</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><TextField required label="Username" value={editUser?.username || ""} onChange={e => setEditUser({ ...editUser, username: e.target.value })} /><TextField type="password" label="New password (optional)" value={editUser?.password || ""} onChange={e => setEditUser({ ...editUser, password: e.target.value })} inputProps={{ minLength: 8 }} /></Stack></DialogContent><DialogActions sx={{ px: 3, pb: 2.5 }}><Button onClick={() => setEditUser(null)}>Cancel</Button><Button type="submit" variant="contained" disabled={saving}>Save changes</Button></DialogActions></Box></Dialog>
  </PageContainer>;
}
